version: '3'

services:
  samba:
    build: .
    image: servercontainers/samba
    restart: always
    environment:
      ACCOUNT_alice: alipass
      ACCOUNT_bob: bobpass
      SAMBA_VOLUME_CONFIG_aliceonly: "[Alice Share]; path=/shares/alice; valid users = alice; guest ok = no; read only = no; browseable = no"
      SAMBA_VOLUME_CONFIG_bobstm: "[TimeCapsule Bob]; path=/shares/timemachine; valid users = bob; guest ok = no; read only = no; browseable = yes"
    volumes:
      - ./shares/alice:/shares/alice
      - ./shares/timemachine:/shares/timemachine
    ports:
      - 139:139
      - 445:445
    networks:
      - samba

networks:
  samba:
    driver: bridge
